version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: deproj-app
    container_name: deproj-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    env_file:
      - .env.docker
    depends_on:
      - pgsql
    ports:
      - "8000:8000"
    command: php artisan serve --host=0.0.0.0 --port=8000

  pgsql:
    image: postgres:15
    container_name: deproj-pgsql
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: deproj
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root0
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
